export const balanceConfig = {
  world: {
    width: 390,
    height: 844,
    defenseLineY: 690,
  },
  player: {
    startX: 195,
    startY: 630,
    width: 45,
    height: 63,
    gravity: 1900,
    jumpPower: 1160,
  },
  combat: {
    attackCooldown: 180,
    slashDuration: 110,
    attackDamage: 40,
    attackDamageVariance: 0.15,
    criticalChance: 0.12,
    criticalMultiplier: 1.5,
    attackRadius: 150,
    attackArcDegrees: 160,
    scorePerHit: 10,
    scorePerKill: 100,
    comboScoreBonus: 5,
    airAttackVelocityMultiplier: 0.08,
    airAttackBrakeDuration: 430,
    airAttackGravityMultiplier: 0.32,
    collisionFallSpeed: 520,
    groundAttackDamageMultiplier: 0.55,
    groundAttackYOffset: 18,
    airAttackYOffset: 8,
    groundAttackRadiusMultiplier: 0.82,
    groundAttackArcMultiplier: 0.84,
    giantSwordRadiusBonus: 24,
    giantSwordCooldownPenalty: 0.07,
    giantSwordShakeDuration: 80,
    giantSwordShakeIntensity: 0.003,
    phantomSwordDelay: 150,
    fireSwordMinBurnDamage: 3,
    fireSwordBaseBurnRate: 0.06,
    fireSwordLevelBurnRate: 0.02,
    fireSwordTicks: 3,
    fireSwordTickInterval: 320,
    lightningSwordBaseRange: 150,
    lightningSwordLevelRange: 18,
    lightningSwordBaseDamageRate: 0.13,
    lightningSwordLevelDamageRate: 0.02,
    lightningSwordBaseChainCount: 3,
    lightningSwordChainCountPerLevel: 2,
    lightningSwordEffectDuration: 160,
    phantomSwordBaseDamageRate: 0.22,
    phantomSwordLevelDamageRate: 0.05,
    phantomSwordEffectDuration: 220,
  },
  burst: {
    cooldown: 60000,
    liftVelocity: 360,
    slowMultiplier: 0.2,
    slowDuration: 1600,
    effectDuration: 420,
    manaCircuitCooldownMultiplier: 0.9,
    earthReboundLiftBonus: 18,
    timeRuneSlowDurationBonus: 220,
    holyBurstBaseDamageRate: 0.14,
    holyBurstLevelDamageRate: 0.03,
    cameraShakeDuration: 180,
    cameraShakeIntensity: 0.006,
  },
  monster: {
    spawnMinX: 125,
    spawnMaxX: 265,
    radius: 36,
    maxHp: 100,
    fallSpeed: 92,
    fallSpeedRandomMin: -12,
    fallSpeedRandomMax: 18,
    hitSlowMultiplier: 0.35,
    hitSlowDuration: 900,
    hitLiftVelocity: 72,
    hitLiftRecovery: 520,
    rotationSpeed: 0.0007,
  },
  effects: {
    slashMarkSizeMultiplier: 2.7,
    slashMarkScaleOutMultiplier: 1.02,
    slashMarkDuration: 260,
  },
  boss: {
    waveInterval: 5,
    baseHp: 5000,
    hpMultiplierPerBossWave: 0.6,
    baseScore: 500,
    scorePerWave: 100,
    spawnX: 195,
    spawnY: -96,
    lifeDamage: 2,
    spawnShakeDuration: 360,
    spawnShakeIntensity: 0.004,
    slashMarkRadiusMultiplier: 0.33,
    slashMarkYOffset: 70,
    liftVelocityMultiplier: 0.18,
    slowMultiplier: 0.78,
    slowDurationMultiplier: 0.45,
  },
  run: {
    startingLife: 3,
    lifeLossScorePenalty: 25,
    lifeLossShakeDuration: 160,
    lifeLossShakeIntensity: 0.009,
    upgradeFreezeDuration: 270,
    upgradeSpawnPauseDuration: 330,
    upgradeFreezeTint: 0x6fb7ff,
    goldPerScore: 0.08,
  },
  upgrades: {
    maxLevel: 4,
  },
  waves: {
    count: 30,
    earlyKillsToNext: [20, 35, 50, 70, 100],
    lateWaveStart: 5,
    lateKillsBase: 100,
    lateKillsPerWave: 28,
    monsterCountMultiplier: 1.5,
    monsterHpBase: 24,
    monsterHpPerWave: 14,
    fallSpeedBase: 88,
    fallSpeedPerWave: 7,
    spawnIntervalMin: 240,
    spawnIntervalBase: 880,
    spawnIntervalReductionPerWave: 30,
    maxAliveBase: 6,
    maxAlivePerWave: 1.1,
    maxAliveCap: 51,
    groupMinBase: 1,
    groupMinWaveDivisor: 1.7,
    groupMinCap: 15,
    groupMaxBase: 3,
    groupMaxWaveDivisor: 1.45,
    groupMaxCap: 21,
    groupSpreadBase: 20,
    groupSpreadPerWave: 1.6,
    groupSpreadCap: 68,
    spawnJitterMin: -10,
    spawnJitterMax: 10,
    spawnStartY: -36,
    spawnStackSpacing: 18,
    smallWeightMin: 6,
    smallWeightBase: 44,
    smallWeightReductionPerWave: 1.25,
    normalWeightMin: 22,
    normalWeightBase: 44,
    normalWeightReductionPerWave: 0.45,
    tankStartWave: 2,
    tankWeightBase: 12,
    tankWeightPerWave: 1.3,
    swiftStartWave: 4,
    swiftWeightBase: 12,
    swiftWeightPerWave: 1.1,
    bruteStartWave: 8,
    bruteWeightBase: 10,
    bruteWeightPerWave: 0.95,
    orbStartWave: 12,
    orbWeightBase: 8,
    orbWeightPerWave: 0.75,
  },
  enemyTypes: {
    small: {
      hpMultiplier: 0.62,
      speedMultiplier: 1.14,
      radius: 24,
      scoreValue: 50,
    },
    normal: {
      hpMultiplier: 1,
      speedMultiplier: 1,
      radius: 34,
      scoreValue: 100,
    },
    tank: {
      hpMultiplier: 1.75,
      speedMultiplier: 0.78,
      radius: 44,
      scoreValue: 200,
    },
    swift: {
      hpMultiplier: 0.82,
      speedMultiplier: 1.36,
      radius: 28,
      scoreValue: 120,
    },
    brute: {
      hpMultiplier: 2.45,
      speedMultiplier: 0.72,
      radius: 50,
      scoreValue: 260,
    },
    orb: {
      hpMultiplier: 1.22,
      speedMultiplier: 1.08,
      radius: 32,
      scoreValue: 180,
    },
    boss: {
      hpMultiplier: 1,
      speedMultiplier: 0.24,
      radius: 228,
      scoreValue: 1000,
    },
  },
} as const;
